image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - _opam/
  only:
  - master@iris/examples
  - /^ci/@iris/examples
  except:
  - triggers
  - schedules
  - api

## Build jobs

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.12.0   coq-iris.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#ci/janno/strict-tc-resolution   coq-iris-heap-lang.dev git git+https://gitlab.mpi-sws.org/iris/iris.git#ci/janno/strict-tc-resolution"
  tags:
  - fp-timing
