image: ralfjung/opam-ci:latest

stages:
  - build

variables:
  CPU_CORES: "10"
  GIT_SUBMODULE_STRATEGY: "recursive"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - master
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.8.7.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.1   coq-mathcomp-ssreflect version 1.6.4"

build-coq.8.6.1:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.6.1   coq-mathcomp-ssreflect version 1.6.4"

build-iris.dev:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.7.1   coq-mathcomp-ssreflect version 1.6.4   coq-iris.dev git https://gitlab.mpi-sws.org/FP/iris-coq.git#$IRIS_REV"
  except:
  only:
  - triggers
  - schedules
